name: CI/CD Pipeline

on:
  push:
    branches: [ dev, staging, main ]
  pull-request:
    branches: [ dev, staging, main ]

env:
    DOCKERHUB_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
    REGISTRY: docker.io
    IMAGE_NAME: flaskapp
    DOCKERHUB_TOKEN: "${{ secrets.DOCKER_TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Builder
        uses: docker/setup-build-action@v1

      - name: login en Docker Hub
        uses: docker/login-action@v1
        with:
            username: "${{ secrets.DOCKER_USERNAME }}"
            password: "${{ secrets.DOCKER_TOKEN }}"
      
      - name: Build & Test
        run:
          # Ejecutar Test sobre Codigo

          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
       
          # Test

      - name: Determinar Environment
        id: Determinar_env
        run: |
            if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "::set-output name=env::prod"
            elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
            echo "::set-output name=env::staging"
            else
            echo "::set-output name=env::dev"
            fi
            
      - name: Deploy        



            